### ISSUE TITLE
Can this work with a prebuild DLL on windows?

### ISSUE THREAD

**Issue by ambikaverma** [jmptbl/python-zint#3]
Hi

I am trying to use the python interface to generate barcodes using zint library.
I was able to import the library and create the zint.symbol object (zint.ZBarcode_Create()) which seems to have all the default data correctly added.

But on calling zint.ZBarcode_Encode (or encode+print or encode+buffer) I don't see any of the associated ouputs such as rows, encoded_data etc.

I just used a pre-built DLL available with the Zint application download.

Code I'm using is below -
import sys
import os

import zint

z = zint.ZBarcode_Create()
z.contents.symbology = zint.BARCODE_CODE39
intxt = zint.instr(str.encode('123456789'))
z.contents.input_mode = 1
print(len(intxt))

res = zint.ZBarcode_Encode_and_Print(z, intxt, 0, 0)
print (res)

print (z.contents.height)
print (z.contents.fgcolour)
print (z.contents.bgcolour)
print (z.contents.outfile)
print (z.contents.option_1)
print (z.contents.scale)
print (z.contents.input_mode)
print (z.contents.text) #empty
print (z.contents.show_hrt)

print (z.contents.encoded_data) #empty
print (z.contents.errtxt) #empty

Note: I do see the value of res above is not 0. But the errtxt field has no data in it.

I can move to Linux environment if that is better or should I build the zint library from scratch?
Any references for building the library from scratch? 

Thanks!

**Comment by jmptbl** [comment]
Sorry, I do not have a Windows setup to provide any assistance with this. I'd welcome feedback if you find the solution though.
